version: '3.8'

services:
  envoy:
    image: envoyproxy/envoy:v1.29-latest
    volumes:
      - ./envoy/https.yaml:/etc/envoy/envoy.yaml
      - ./certs:/certs
    ports:
      - "80:80" # Http
      - "443:443" # Https
    networks:
      - envoymesh
  
  go-1111:
    build:
      context: ./go
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "1111:1111"
    environment:
      - PORT=1111

  go-2222:
    build:
      context: ./go
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "2222:2222"
    environment:
      - PORT=2222

networks:
  envoymesh:
    driver: bridge