# Use official Node.js image as base
FROM node:20-alpine

# Set working directory inside the container
WORKDIR /app

# Copy rest of the application
COPY . .

# Expose port (default to 3000)
ARG PORT=3000
ENV PORT=${PORT}
EXPOSE ${PORT}

# Command to run the application
CMD ["node", "index.js"]
